# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7bd1411ee14707c0a0964f0123fedf338536b50e77807f6924270f40eb590f3c1d4c55189a6a9204d312310f244434da5a076458041369b2d73210bc97c7d7

test:
  secret_key_base: a08f42c67aeaffc29a9bef2c8c581e349d3bd27fa487c0f0121cb9b17e77c4b3c625021be72d15b309b2035218286b91bf0f6ce8bddb5572b93faf62ccb0edcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
